// <auto-generated />
using System;
using ASP.NET_Core3.x_WebApi_Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ASP.NET_Core3.x_WebApi_Demo.Migrations
{
    [DbContext(typeof(DemoDbContext))]
    partial class DemoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("ASP.NET_Core3.x_WebApi_Demo.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa2ee05c-029b-4830-be6e-44df5923716c"),
                            Code = "KJ",
                            Name = "财务部"
                        },
                        new
                        {
                            Id = new Guid("6fb600c1-9011-4fd7-9234-881379716440"),
                            Code = "RS",
                            Name = "人事部"
                        },
                        new
                        {
                            Id = new Guid("5efc910b-2f45-43df-afae-620d40542853"),
                            Code = "YF",
                            Name = "研发部"
                        },
                        new
                        {
                            Id = new Guid("bbdee09c-089b-4d30-bece-44df59237100"),
                            Code = "HQ",
                            Name = "后勤部"
                        },
                        new
                        {
                            Id = new Guid("6fb600c1-9011-4fd7-9234-881379716400"),
                            Code = "GL",
                            Name = "管理部"
                        },
                        new
                        {
                            Id = new Guid("6eaa53e1-9011-4fd7-9234-881379716400"),
                            Code = "XC",
                            Name = "宣传部"
                        });
                });

            modelBuilder.Entity("ASP.NET_Core3.x_WebApi_Demo.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b501cb3-d168-4cc0-b375-48fb33f318a4"),
                            BirthDay = new DateTime(1976, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("5efc910b-2f45-43df-afae-620d40542853"),
                            EmployeeNo = "52314",
                            Gender = 1,
                            Name = "张文远"
                        },
                        new
                        {
                            Id = new Guid("7eaa532c-1be5-472c-a738-94fd26e5fad6"),
                            BirthDay = new DateTime(1981, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("6fb600c1-9011-4fd7-9234-881379716400"),
                            EmployeeNo = "X5412",
                            Gender = 1,
                            Name = "曹孟德"
                        },
                        new
                        {
                            Id = new Guid("72457e73-ea34-4e02-b575-8d384e82a481"),
                            BirthDay = new DateTime(1986, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("6eaa53e1-9011-4fd7-9234-881379716400"),
                            EmployeeNo = "G3003",
                            Gender = 0,
                            Name = "孙尚香"
                        },
                        new
                        {
                            Id = new Guid("7644b71d-d74e-43e2-ac32-8cbadd7b1c3a"),
                            BirthDay = new DateTime(1977, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("5efc910b-2f45-43df-afae-620d40542853"),
                            EmployeeNo = "45097",
                            Gender = 1,
                            Name = "关云长"
                        },
                        new
                        {
                            Id = new Guid("679dfd33-32e4-4393-b061-f7abb8956f53"),
                            BirthDay = new DateTime(1967, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("6fb600c1-9011-4fd7-9234-881379716440"),
                            EmployeeNo = "76009",
                            Gender = 1,
                            Name = "鲁子敬"
                        },
                        new
                        {
                            Id = new Guid("1861341e-b42b-410c-ae21-cf11f36fc574"),
                            BirthDay = new DateTime(1987, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("6fb600c1-9011-4fd7-9234-881379716400"),
                            EmployeeNo = "34404",
                            Gender = 1,
                            Name = "诸葛孔明"
                        },
                        new
                        {
                            Id = new Guid("1896341e-b45b-410c-ae21-cf11f16fc574"),
                            BirthDay = new DateTime(1977, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = new Guid("5efc910b-2f45-43df-afae-620d40542853"),
                            EmployeeNo = "521404",
                            Gender = 1,
                            Name = "赵子龙"
                        });
                });

            modelBuilder.Entity("ASP.NET_Core3.x_WebApi_Demo.Entities.Employee", b =>
                {
                    b.HasOne("ASP.NET_Core3.x_WebApi_Demo.Entities.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
